### ISSUE TITLE
Unable to autolaunch a dbus-daemon

### ISSUE THREAD

**Issue by morgoth** [and3rson/clay#54]
Hey, I'm trying to run clay on Ubuntu server 18.04
I'm getting error:
```
Traceback (most recent call last):
  File "/home/wojtek/.local/bin/clay", line 7, in <module>
    from clay.app import main
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/app.py", line 16, in <module>
    from clay.player import player
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/player.py", line 19, in <module>
    from clay.osd import osd_manager
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/osd.py", line 61, in <module>
    osd_manager = _OSDManager()  # pylint: disable=invalid-name
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/osd.py", line 31, in __init__
    self.bus = SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```
so I  tried to `export DISPLAY=:0`, but know I'm getting:
```
Traceback (most recent call last):
  File "/home/wojtek/.local/bin/clay", line 7, in <module>
    from clay.app import main
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/app.py", line 16, in <module>
    from clay.player import player
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/player.py", line 19, in <module>
    from clay.osd import osd_manager
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/osd.py", line 61, in <module>
    osd_manager = _OSDManager()  # pylint: disable=invalid-name
  File "/home/wojtek/.local/lib/python2.7/site-packages/clay/osd.py", line 31, in __init__
    self.bus = SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```
Do you know what can be wrong?

**Comment by ValentijnvdBeek** [comment]
Hi Morgoth, 

It is trying to launch the XDG notification services but it is failing since you don't have X11 installed. This *should* be fixed in the development branch (porcelain) but that has been taking forever to merge.

Commenting out line 61 in clay/osd.py and line 421 in clay/player.py should work
